// The 48 Laws of Power (Robert Greene), boiled down for daily use.
// mode "use"    → a healthy way to apply the law.
// mode "defend" → a manipulative law: how to spot it and protect yourself.
// area tags the real-life example: business | school | sports | social.

export const LAW_AREAS = {
  business: "Business",
  school: "School",
  sports: "Sports & cadets",
  social: "Friends & social",
};

export const LAWS = [
  { n: 1, title: "Never outshine the master", idea: "Make the people above you feel secure, not threatened.", mode: "use",
    tip: "Let the person in charge own the direction while you deliver the results.", area: "school",
    example: "In a group project with a strong leader, back their plan in public and pitch your improvements one-on-one." },
  { n: 2, title: "Don't put too much trust in friends; learn to use enemies", idea: "Friends can get comfortable or jealous. Rivals often work harder to prove themselves.", mode: "use",
    tip: "Keep money and business separate from friendship, with clear terms written down.", area: "business",
    example: "If a friend wants to \"partner\" on Intelligent Automations, write down who does what and who gets paid what first." },
  { n: 3, title: "Conceal your intentions", idea: "People can block what they see coming.", mode: "use",
    tip: "Build first, announce after. Talk about results, not plans.", area: "business",
    example: "Don't tell everyone about your app idea. Show them when it works." },
  { n: 4, title: "Always say less than necessary", idea: "The more you talk, the more likely you say something you regret. Short answers sound confident.", mode: "use",
    tip: "Make your point, then stop. Let silence do the work.", area: "business",
    example: "On a sales call, say your price and then stop talking. Wait for them." },
  { n: 5, title: "Guard your reputation with your life", idea: "Your reputation walks into the room before you do.", mode: "use",
    tip: "Deliver on time, every time. One broken promise costs more than ten kept ones earn.", area: "business",
    example: "Every business you work for in Markham is a future referral. Never miss a deadline you set." },
  { n: 6, title: "Court attention at all costs", idea: "Being invisible is worse than being criticized.", mode: "use",
    tip: "Get known for something real and specific, not for being loud.", area: "social",
    example: "Be \"the guy who builds websites and AI tools.\" Share what you make instead of hiding it." },
  { n: 7, title: "Get others to do the work, but take the credit", idea: "Some people let others do the work and then grab the spotlight.", mode: "defend",
    tip: "Spot it: quiet during the work, loud during the presentation. Defend: make your contribution visible early.", area: "school",
    example: "In group projects, post your part in the shared doc early so the version history shows who did what." },
  { n: 8, title: "Make other people come to you", idea: "Whoever makes the other side come to them controls the game.", mode: "use",
    tip: "Create something valuable that pulls people in instead of chasing them.", area: "business",
    example: "A free 10-minute AI audit or a demo site pulls clients in better than begging for work in DMs." },
  { n: 9, title: "Win through actions, never through argument", idea: "Arguments create resentment. Results end the debate.", mode: "use",
    tip: "Stop debating. Demonstrate.", area: "sports",
    example: "Don't argue with the coach about playing time. Beat the starter in practice." },
  { n: 10, title: "Avoid the unhappy and unlucky", idea: "Chronic negativity and chaos are contagious.", mode: "use",
    tip: "Be kind, but limit time with people who always complain and never change.", area: "social",
    example: "If a group is always in drama, spend more time with people who are building something." },
  { n: 11, title: "Keep people dependent on you", idea: "The more people need you, the more secure your position.", mode: "use",
    tip: "Healthy version: be so good at something that you're hard to replace. Never hold people hostage.", area: "business",
    example: "Offer monthly website and chatbot maintenance. Clients rely on you and you get recurring income." },
  { n: 12, title: "Use selective honesty and generosity to disarm", idea: "One honest move or surprise gift can lower someone's guard.", mode: "defend",
    tip: "Spot it: sudden generosity right before a big ask. Defend: judge the ask on its own, not the gift.", area: "social",
    example: "If someone suddenly does you a big favour and then asks for your homework, the favour was the setup." },
  { n: 13, title: "Appeal to self-interest, not mercy", idea: "People help when they see what's in it for them.", mode: "use",
    tip: "Show people what they get, not what you need.", area: "business",
    example: "Don't say \"I need clients.\" Say \"This chatbot answers customers at 2 a.m. so you stop losing orders.\"" },
  { n: 14, title: "Pose as a friend, work as a spy", idea: "Some people get close just to gather information.", mode: "defend",
    tip: "Spot it: lots of questions about your plans, little shared back. Defend: keep plans and numbers private until they're done.", area: "business",
    example: "A \"curious\" competitor asking about your prices and tools isn't trying to be your friend." },
  { n: 15, title: "Crush your enemy totally", idea: "A half-beaten opponent comes back.", mode: "use",
    tip: "Keep it to competition, not people: when you're ahead, finish the job.", area: "sports",
    example: "Up by 10 in the fourth quarter? Keep the pressure on until the buzzer." },
  { n: 16, title: "Use absence to increase respect", idea: "What's always available gets taken for granted.", mode: "use",
    tip: "Don't be available 24/7. Scarcity raises your value.", area: "business",
    example: "Answer clients during set hours, not instantly at 11 p.m. It looks professional and protects your sleep." },
  { n: 17, title: "Keep others in suspense: be unpredictable", idea: "Some people keep everyone guessing so they stay in control.", mode: "defend",
    tip: "Spot it: hot-and-cold moods that make everyone tiptoe. Defend: stay consistent and don't rearrange your life around their moods.", area: "social",
    example: "A friend who's warm one day and ignores you the next? Stay steady and don't chase." },
  { n: 18, title: "Don't build fortresses: isolation is dangerous", idea: "Cutting yourself off cuts you off from help and information.", mode: "use",
    tip: "Stay connected, especially when things get hard.", area: "school",
    example: "Struggling in French or English? See the teacher or join a study group instead of grinding alone." },
  { n: 19, title: "Know who you're dealing with", idea: "Some people hold grudges or power. Read people before you push.", mode: "use",
    tip: "Figure out someone's pride, power and patience before you challenge them.", area: "sports",
    example: "In cadets, know the chain of command and respect senior cadets, even when you disagree." },
  { n: 20, title: "Don't commit to anyone", idea: "Staying independent keeps your options open.", mode: "use",
    tip: "Don't get dragged into other people's fights.", area: "social",
    example: "When two friends are fighting, stay friendly with both and don't pick a side." },
  { n: 21, title: "Play a sucker to catch a sucker", idea: "Acting clueless makes others overconfident and careless.", mode: "defend",
    tip: "Spot it: someone who \"doesn't get it\" suspiciously often. Defend: say less (Law 4) and get terms in writing.", area: "business",
    example: "A client saying \"I don't really understand tech\" may still know exactly what a website should cost." },
  { n: 22, title: "Use the surrender tactic", idea: "When you can't win a fight, backing down calmly keeps your strength for later.", mode: "use",
    tip: "Lose gracefully now, rebuild, and win the next round.", area: "school",
    example: "Lost an argument about a mark? Accept it calmly, then ask exactly what gets full marks next time." },
  { n: 23, title: "Concentrate your forces", idea: "Spreading yourself thin weakens everything.", mode: "use",
    tip: "Pick one target and hit it until it works.", area: "business",
    example: "Land one paying AI client before starting three new side projects." },
  { n: 24, title: "Play the perfect courtier", idea: "Around people with power, be polite, useful and low-drama.", mode: "use",
    tip: "Make your superiors look good, do your job well, and don't over-flatter.", area: "sports",
    example: "In cadets: show up early, uniform sharp, job done right. That's how people get promoted." },
  { n: 25, title: "Re-create yourself", idea: "You don't have to accept the role others give you.", mode: "use",
    tip: "Decide who you want to be and build that identity on purpose.", area: "school",
    example: "Want to be a 90% student? Start acting like one this week: homework first, phone away." },
  { n: 26, title: "Keep your hands clean", idea: "Some people use others to do their dirty work so they look innocent.", mode: "defend",
    tip: "Spot it: someone never directly involved, but always near the drama. Defend: don't be anyone's messenger.", area: "social",
    example: "If someone asks you to \"go tell her what she said,\" you're being used." },
  { n: 27, title: "Play on people's need to believe", idea: "People crave something to believe in, and some sell it to them.", mode: "defend",
    tip: "Spot it: big promises, a charismatic leader, and pressure to buy in fast. Defend: ask for proof and real results.", area: "business",
    example: "Be skeptical of influencers selling $997 \"get rich with AI\" courses. Build real skills instead." },
  { n: 28, title: "Enter action with boldness", idea: "Hesitation shows, and people pounce on it.", mode: "use",
    tip: "Once you decide, commit fully. Mistakes made boldly are easier to fix.", area: "business",
    example: "Walk into a local business, make eye contact, and pitch like you belong there." },
  { n: 29, title: "Plan all the way to the end", idea: "Know where you're going before you start.", mode: "use",
    tip: "Define what \"done\" looks like before step one.", area: "school",
    example: "For essays, write your conclusion's main point first. Every paragraph then has a target." },
  { n: 30, title: "Make your accomplishments seem effortless", idea: "Visible struggle makes people doubt you.", mode: "use",
    tip: "Put in the hard work in private so the performance looks smooth.", area: "sports",
    example: "The sprinter who looks relaxed at the finish practiced staying relaxed at top speed." },
  { n: 31, title: "Control the options", idea: "Whoever sets the choices controls the outcome.", mode: "use",
    tip: "Give people a few choices you're happy with instead of an open question.", area: "business",
    example: "Offer three packages (Basic, Standard, Premium) instead of asking \"what's your budget?\"" },
  { n: 32, title: "Play to people's fantasies", idea: "People fall for what they wish were true.", mode: "defend",
    tip: "Spot it: an offer promising exactly what you dream of with no effort. Defend: if it's too good to be true, it is.", area: "social",
    example: "\"Make $5,000 a week from your phone\" posts are selling a fantasy, not a plan." },
  { n: 33, title: "Discover each person's weak spot", idea: "Everyone has an insecurity that can be used as leverage.", mode: "defend",
    tip: "Spot it: someone who finds your insecurity and keeps poking it. Defend: know your own weak spots so nobody can use them.", area: "social",
    example: "If someone keeps joking about the thing you're sensitive about, it's not a joke. Name it or walk away." },
  { n: 34, title: "Act like a king to be treated like one", idea: "People treat you the way you carry yourself.", mode: "use",
    tip: "Carry yourself with quiet confidence. Don't apologize for your value.", area: "business",
    example: "State your prices confidently. Never say \"sorry, it's kind of expensive.\"" },
  { n: 35, title: "Master the art of timing", idea: "The same move can fail or succeed depending on when you make it.", mode: "use",
    tip: "Be patient, then move fast when the moment is right.", area: "school",
    example: "Ask for an extension a week early, not the night before it's due." },
  { n: 36, title: "Disdain things you cannot have", idea: "Attention feeds what you're upset about. Ignoring it takes its power.", mode: "use",
    tip: "Don't obsess over what you lost. Put the energy into your own goals.", area: "social",
    example: "Left out of a group chat? Don't complain. Go put in work on your goals." },
  { n: 37, title: "Create compelling spectacles", idea: "People remember what they see more than what they hear.", mode: "use",
    tip: "Show, don't tell. Make it visual.", area: "business",
    example: "A live demo where the chatbot answers the owner's real question beats any slideshow." },
  { n: 38, title: "Think as you like, but behave like others", idea: "Flaunting that you're different makes people defensive.", mode: "use",
    tip: "Keep your unusual ideas, but pick your battles in how you act.", area: "school",
    example: "You can think a school rule is pointless, but follow it and save your energy for what matters." },
  { n: 39, title: "Stir up waters to catch fish", idea: "Angry people make mistakes, so some people try to make you angry.", mode: "defend",
    tip: "Spot it: trash talk or baiting meant to make you react. Defend: stay cold and stick to the plan.", area: "sports",
    example: "Trash talk on the court is meant to make you foul. Stay calm and let the scoreboard answer." },
  { n: 40, title: "Despise the free lunch", idea: "What's free often comes with hidden strings, and people don't value free work.", mode: "use",
    tip: "Pay for what matters, and charge for your work.", area: "business",
    example: "Stop building free websites \"for exposure.\" Charge something, even a small amount." },
  { n: 41, title: "Avoid stepping into a great person's shoes", idea: "If you copy someone great, you'll always be compared to them.", mode: "use",
    tip: "Build your own lane instead of being a copy.", area: "sports",
    example: "Replacing a star senior on the team? Don't copy their game. Win your own way." },
  { n: 42, title: "Strike the shepherd and the sheep will scatter", idea: "Trouble in a group usually starts with one person.", mode: "use",
    tip: "Deal with the root of a problem, not every person around it.", area: "sports",
    example: "If one cadet keeps stirring up the section, talk to them (or a senior cadet) directly instead of fighting everyone." },
  { n: 43, title: "Work on the hearts and minds of others", idea: "Force creates resistance. Understanding creates loyalty.", mode: "use",
    tip: "Learn what people care about before you ask for anything.", area: "business",
    example: "Ask a business owner about their story and biggest headache before you pitch. People buy from people who get them." },
  { n: 44, title: "Disarm with the mirror effect", idea: "People feel comfortable around people who reflect them.", mode: "use",
    tip: "Mirror people's words, pace and energy to build rapport.", area: "school",
    example: "On essays, use the exact words from the rubric and question. It shows the teacher exactly what they asked for." },
  { n: 45, title: "Preach change, but don't reform too much at once", idea: "Too much change at once scares people.", mode: "use",
    tip: "Introduce change in small steps that feel safe.", area: "business",
    example: "A client scared of tech? Automate one small task first, not the whole business." },
  { n: 46, title: "Never appear too perfect", idea: "Looking flawless makes people envious and distant.", mode: "use",
    tip: "Admit small flaws and laugh at yourself.", area: "social",
    example: "Laugh at your own mistakes. People trust someone who isn't pretending." },
  { n: 47, title: "Don't go past the mark you aimed for", idea: "Winning makes people overconfident. Know when to stop.", mode: "use",
    tip: "When you've won, lock it in and stop pushing.", area: "business",
    example: "Client said yes? Stop selling, confirm the details, and leave on a high note." },
  { n: 48, title: "Assume formlessness", idea: "Being rigid makes you predictable. Adaptable is hard to beat.", mode: "use",
    tip: "Stay flexible and adjust to what's in front of you.", area: "sports",
    example: "If the defence takes away your drive, pass, shoot or cut. Don't force one move." },
];

// Law 1 lands on this date, then one law per day in order, looping every 48 days.
const LAW_EPOCH_UTC = Date.UTC(2026, 8, 27);

export function lawIndexForDate(dateKey) {
  const [year, month, day] = dateKey.split("-").map(Number);
  const days = Math.round((Date.UTC(year, month - 1, day) - LAW_EPOCH_UTC) / 86400000);
  return ((days % LAWS.length) + LAWS.length) % LAWS.length;
}

export function lawForDate(dateKey) {
  return LAWS[lawIndexForDate(dateKey)];
}

export function isLawsPath(pathname = "") {
  return /^\/laws\/?$/.test(pathname);
}
