// Additional practice content. Each work example keeps the same fields as a
// speak topic so it can flow through resolveRound without UI changes.
const WORK_EXAMPLE_SPECS = [
  ["Explain the launch plan for a school recycling drive.", "pip", "state-the-location"],
  ["Pitch a safer warm-up routine to a track coach.", "prep", "describe-actions"],
  ["Explain how a student-run tutoring club should schedule volunteers.", "bab", "use-dialogue"],
  ["Argue for a quiet study hour in the school library.", "pcs", "share-your-thoughts"],
  ["Explain a customer onboarding flow for a small software product.", "five-ws", "sensory-anchor"],
  ["Pitch a better way for a café to reduce food waste.", "bab", "state-the-location"],
  ["Argue for four-day shift planning at a busy retail store.", "prep", "status-shift"],
  ["Explain how a community garden could share its harvest.", "five-ws", "describe-actions"],
  ["Pitch a volunteer check-in system for a food bank.", "pip", "use-dialogue"],
  ["Argue for adding captions to every school assembly video.", "pcs", "show-emotions"],
  ["Explain how a clinic receptionist should protect patient privacy.", "five-ws", "state-the-location"],
  ["Pitch a simple dashboard for a nonprofit fundraiser.", "bab", "sensory-anchor"],
  ["Argue that a sports team should track recovery, not only results.", "prep", "share-your-thoughts"],
  ["Explain the roles in a neighborhood emergency plan.", "five-ws", "describe-actions"],
  ["Pitch a mentoring program for new employees at a warehouse.", "pip", "use-dialogue"],
  ["Argue for a paperless permission process at a youth camp.", "pcs", "status-shift"],
  ["Explain how a museum could make one exhibit accessible.", "five-ws", "sensory-anchor"],
  ["Pitch a weekly artist feedback circle.", "bab", "state-the-location"],
  ["Argue for a transparent waitlist at a community gym.", "prep", "share-your-thoughts"],
  ["Explain how a restaurant kitchen can reduce order mistakes.", "five-ws", "describe-actions"],
  ["Pitch a buddy system for students arriving at a new school.", "pip", "use-dialogue"],
  ["Argue for replacing one plastic item in a hotel room.", "pcs", "show-emotions"],
  ["Explain how a local newspaper should verify a tip.", "five-ws", "state-the-location"],
  ["Pitch a better calendar for a family health practice.", "bab", "sensory-anchor"],
  ["Argue for a beginner division in a city sports league.", "prep", "status-shift"],
  ["Explain how a school fundraiser reaches its goal.", "five-ws", "use-dialogue"],
  ["Pitch a repair café for broken household items.", "pip", "describe-actions"],
  ["Argue for a no-phone first ten minutes in team meetings.", "pcs", "share-your-thoughts"],
  ["Explain how a photographer prepares a client brief.", "five-ws", "sensory-anchor"],
  ["Pitch a walking route that connects three public parks.", "bab", "state-the-location"],
  ["Argue for clearer labels on a grocery store's local products.", "prep", "status-shift"],
  ["Explain how a robotics team tests a new design.", "five-ws", "describe-actions"],
  ["Pitch a study app feature that rewards consistency.", "pip", "use-dialogue"],
  ["Argue for a dedicated rest area at a tournament.", "pcs", "show-emotions"],
  ["Explain how a theater crew manages a quick costume change.", "five-ws", "state-the-location"],
  ["Pitch a shared equipment library for a school.", "bab", "sensory-anchor"],
  ["Argue for a shorter application form at a youth nonprofit.", "prep", "share-your-thoughts"],
  ["Explain the handoff between a designer and a developer.", "five-ws", "describe-actions"],
  ["Pitch a weekend skills workshop for first-generation students.", "pip", "use-dialogue"],
  ["Argue for publishing a charity's monthly spending summary.", "pcs", "status-shift"],
  ["Explain how a barbershop could manage walk-ins fairly.", "five-ws", "sensory-anchor"],
  ["Pitch a neighborhood tool-sharing shelf.", "bab", "state-the-location"],
  ["Argue for a real lunch break in a high-pressure office.", "prep", "show-emotions"],
  ["Explain how a science fair judge can give useful feedback.", "five-ws", "describe-actions"],
  ["Pitch an audio guide for visitors with low vision.", "pip", "use-dialogue"],
  ["Argue for safer lighting around a transit stop.", "pcs", "sensory-anchor"],
  ["Explain how an independent author launches a book.", "five-ws", "state-the-location"],
  ["Pitch a practice plan for a beginner orchestra section.", "bab", "status-shift"],
  ["Argue for keeping a public swimming pool open later.", "prep", "share-your-thoughts"],
  ["Explain how a farm stand forecasts Saturday demand.", "five-ws", "describe-actions"],
  ["Pitch a clearer way to report a broken streetlight.", "pip", "use-dialogue"],
  ["Argue for teaching basic cooking in middle school.", "pcs", "show-emotions"],
  ["Explain how a podcast team researches an interview.", "five-ws", "sensory-anchor"],
  ["Pitch a mentorship ladder for a youth coding club.", "bab", "state-the-location"],
  ["Argue for visible allergy information at every event.", "prep", "status-shift"],
  ["Explain how a delivery team chooses efficient routes.", "five-ws", "describe-actions"],
  ["Pitch a low-cost arts night for a community center.", "pip", "use-dialogue"],
  ["Argue for a four-week trial before buying new software.", "pcs", "share-your-thoughts"],
  ["Explain how a gardener restores tired soil.", "five-ws", "sensory-anchor"],
  ["Pitch a more welcoming sign-in desk at a shelter.", "bab", "state-the-location"],
  ["Argue for publishing the criteria for team selection.", "prep", "show-emotions"],
  ["Explain how a film crew keeps a shoot on schedule.", "five-ws", "describe-actions"],
  ["Pitch a quiet sensory room at a recreation center.", "pip", "use-dialogue"],
  ["Argue for free menstrual products in school washrooms.", "pcs", "status-shift"],
  ["Explain how a beekeeper protects a hive through winter.", "five-ws", "sensory-anchor"],
  ["Pitch a peer review ritual for a student newspaper.", "bab", "state-the-location"],
  ["Argue for paying interns a fair hourly wage.", "prep", "share-your-thoughts"],
  ["Explain how a bike shop diagnoses a difficult repair.", "five-ws", "describe-actions"],
  ["Pitch a shared reading list for a new team.", "pip", "use-dialogue"],
  ["Argue for a slower, safer process in a busy kitchen.", "pcs", "show-emotions"],
  ["Explain how a translator prepares for a medical appointment.", "five-ws", "state-the-location"],
  ["Pitch a donation matching day for a shelter.", "bab", "sensory-anchor"],
  ["Argue for a visible queue at a popular food truck.", "prep", "status-shift"],
  ["Explain how a carpenter turns a sketch into a shelf.", "five-ws", "describe-actions"],
  ["Pitch a beginner-friendly public speaking circle.", "pip", "use-dialogue"],
  ["Argue for automatic savings lessons in a youth program.", "pcs", "share-your-thoughts"],
  ["Explain how a florist handles a last-minute wedding order.", "five-ws", "sensory-anchor"],
  ["Pitch a neighborhood map of wheelchair-accessible entrances.", "bab", "state-the-location"],
  ["Argue for publishing corrections prominently in a magazine.", "prep", "show-emotions"],
  ["Explain how an electrician plans a safe inspection.", "five-ws", "describe-actions"],
  ["Pitch a welcome guide for exchange students.", "pip", "use-dialogue"],
  ["Argue for measuring team health with regular check-ins.", "pcs", "status-shift"],
  ["Explain how a baker scales a recipe for a festival.", "five-ws", "sensory-anchor"],
  ["Pitch a rotating leadership role in a volunteer crew.", "bab", "state-the-location"],
  ["Argue for an earlier warning when a bus route changes.", "prep", "share-your-thoughts"],
  ["Explain how a web developer handles a production bug.", "five-ws", "describe-actions"],
  ["Pitch a calm corner in a crowded community event.", "pip", "use-dialogue"],
  ["Argue for replacing a confusing form with a conversation.", "pcs", "show-emotions"],
  ["Explain how a coach adjusts practice for heat.", "five-ws", "state-the-location"],
  ["Pitch a monthly showcase for local makers.", "bab", "sensory-anchor"],
  ["Argue for a second chance policy after a missed deadline.", "prep", "status-shift"],
  ["Explain how a librarian chooses books for a new collection.", "five-ws", "describe-actions"],
  ["Pitch a simple feedback form after every workshop.", "pip", "use-dialogue"],
  ["Argue for keeping one day a week meeting-free.", "pcs", "share-your-thoughts"],
  ["Explain how a tailor prepares a garment fitting.", "five-ws", "sensory-anchor"],
  ["Pitch a rideshare board for after-school activities.", "bab", "state-the-location"],
  ["Argue for investing in staff training before new equipment.", "prep", "show-emotions"],
  ["Explain how a veterinarian prepares a nervous animal.", "five-ws", "describe-actions"],
  ["Pitch a public scoreboard for a community goal.", "pip", "use-dialogue"],
  ["Argue for a simple emergency contact card in every backpack.", "pcs", "status-shift"],
  ["Explain how a mechanic communicates an unexpected repair.", "five-ws", "sensory-anchor"],
  ["Pitch a creative challenge that connects students across grades.", "bab", "state-the-location"],
  ["Argue for celebrating reliable effort, not only top results.", "prep", "share-your-thoughts"],
  ["Explain how a translator keeps a group conversation balanced.", "five-ws", "describe-actions"],
  ["Pitch a lending program for sports shoes and equipment.", "pip", "use-dialogue"],
  ["Argue for a clear owner on every team decision.", "pcs", "show-emotions"],
  ["Explain how a museum volunteer handles a difficult question.", "five-ws", "state-the-location"],
  ["Pitch a five-minute reset between demanding classes.", "bab", "sensory-anchor"],
  ["Argue for keeping a written record of lessons learned.", "prep", "status-shift"],
  ["Explain how a community choir prepares for its first concert.", "five-ws", "describe-actions"],
  ["Pitch a small grant for student-led experiments.", "pip", "use-dialogue"],
  ["Argue for making rest part of every training plan.", "pcs", "share-your-thoughts"],
  ["Explain how a florist recovers after a delivery delay.", "five-ws", "sensory-anchor"],
  ["Pitch a public thank-you wall for volunteers.", "bab", "state-the-location"],
  ["Argue for documenting a process before automating it.", "prep", "show-emotions"],
  ["Explain how a startup tests an idea with ten real users.", "five-ws", "describe-actions"],
  ["Pitch a weekly office hour for questions people avoid asking.", "pip", "use-dialogue"],
  ["Argue for designing services with the quietest user in mind.", "pcs", "status-shift"],
];

export const workExamples = WORK_EXAMPLE_SPECS.map(([text, framework, technique]) => ({
  kind: "explain", text, framework, technique,
}));

export const motivationalStories = [
  { kind: "story", text: "Tell the story of a runner who rebuilt confidence after finishing last.", framework: "star", technique: "show-emotions", setup: "A young runner finished last at a crowded meet.", struggle: "They wanted to quit because every result felt like proof they did not belong.", turningPoint: "A coach asked them to train one honest lap at a time and record effort instead of place.", lesson: "Progress becomes visible when the measure changes from comparison to consistency." },
  { kind: "story", text: "Tell the story of a student who learned to ask for help before a major exam.", framework: "ppf", technique: "use-dialogue", setup: "A student kept hiding confusion behind neat notes.", struggle: "By exam week, the gaps were too large to ignore and embarrassment made them silent.", turningPoint: "They brought one question to a teacher every morning and built a study group.", lesson: "Asking early is a form of discipline, not a confession of weakness." },
  { kind: "story", text: "Tell the story of a family business that survived one difficult season.", framework: "star", technique: "state-the-location", setup: "A small bakery lost its biggest weekend customer.", struggle: "Bills stayed fixed while the empty shelves made the future feel smaller.", turningPoint: "The family began taking preorders, learning delivery routes, and calling every regular personally.", lesson: "A setback can become a redesign when people stay close to the work." },
  { kind: "story", text: "Tell the story of an artist who kept practicing after repeated rejection.", framework: "ppf", technique: "sensory-anchor", setup: "An illustrator pinned rejection emails beside a blank desk.", struggle: "For months, every submission returned without a yes.", turningPoint: "They made one small drawing daily and shared the process instead of waiting for permission.", lesson: "Discipline protects the craft while recognition catches up." },
  { kind: "story", text: "Tell the story of a volunteer who turned a lonely shelter shift into a community.", framework: "star", technique: "describe-actions", setup: "One volunteer arrived at a quiet shelter with no plan beyond serving dinner.", struggle: "The first shifts felt awkward and nobody knew how to start a conversation.", turningPoint: "They began remembering names, setting one table aside for stories, and inviting others to help.", lesson: "Belonging is often built from small repeated acts of attention." },
  { kind: "story", text: "Tell the story of a coder who fixed a product by listening to one frustrated user.", framework: "star", technique: "use-dialogue", setup: "A new app looked polished but users kept abandoning it.", struggle: "The team argued over features instead of understanding the failure.", turningPoint: "One user said, 'I never knew what to do next,' and the team rebuilt the first screen around that sentence.", lesson: "Good work starts when pride makes room for evidence." },
  { kind: "story", text: "Tell the story of a swimmer who returned after an injury.", framework: "ppf", technique: "show-emotions", setup: "A swimmer watched teammates train while their shoulder healed.", struggle: "Recovery was slow, repetitive, and invisible compared with race-day progress.", turningPoint: "They followed the boring exercises, celebrated pain-free movement, and returned for one event instead of a whole season.", lesson: "Patience is not standing still; it is the work that makes a return possible." },
  { kind: "story", text: "Tell the story of a teacher who changed one classroom routine.", framework: "bab", technique: "state-the-location", setup: "A classroom started every morning noisy and scattered.", struggle: "Students missed instructions and the teacher spent energy correcting instead of teaching.", turningPoint: "They introduced a two-minute written start and greeted each student at the door.", lesson: "Small structure can release a surprising amount of human attention." },
  { kind: "story", text: "Tell the story of a newcomer who became the person others welcomed.", framework: "ppf", technique: "sensory-anchor", setup: "A newcomer ate lunch alone in a loud school cafeteria.", struggle: "They waited for someone else to make the first move and felt unseen.", turningPoint: "After joining one club, they began inviting the next new student to sit with them.", lesson: "The belonging we want often begins with the welcome we choose to offer." },
  { kind: "story", text: "Tell the story of a musician who learned a difficult piece one measure at a time.", framework: "star", technique: "describe-actions", setup: "A pianist faced a piece that seemed too fast to play.", struggle: "Full run-throughs ended in the same mistakes and confidence fell each night.", turningPoint: "They slowed the metronome, isolated two measures, and practiced the transitions for weeks.", lesson: "A large challenge becomes workable when attention narrows to the next repeat." },
  { kind: "story", text: "Tell the story of a parent who built a healthier routine during a hard year.", framework: "ppf", technique: "share-your-thoughts", setup: "A parent felt tired before the day had properly started.", struggle: "Big health plans collapsed under work, family, and worry.", turningPoint: "They chose a ten-minute walk after dinner and protected it like an appointment.", lesson: "Sustainable change begins small enough to survive an imperfect week." },
  { kind: "story", text: "Tell the story of a team that lost its leader and found shared leadership.", framework: "star", technique: "use-dialogue", setup: "A volunteer team lost its organizer before its biggest event.", struggle: "Everyone waited for instructions that no longer came.", turningPoint: "One member said, 'We can each own one piece,' and the group divided the work openly.", lesson: "Leadership can be distributed when responsibility becomes visible." },
  { kind: "story", text: "Tell the story of a researcher whose failed experiment led to a better question.", framework: "bab", technique: "sensory-anchor", setup: "A lab experiment produced a result that made no sense.", struggle: "Weeks of preparation seemed wasted and the first instinct was to hide the error.", turningPoint: "The researcher repeated the test, found the pattern, and asked a narrower question.", lesson: "Failure becomes useful when it is examined honestly instead of defended." },
  { kind: "story", text: "Tell the story of a coach who learned to measure the person, not only the score.", framework: "star", technique: "status-shift", setup: "A coach judged every practice by the scoreboard.", struggle: "Athletes became afraid to experiment and quieter players disappeared.", turningPoint: "The coach began praising communication, recovery, and brave attempts alongside results.", lesson: "The metric you celebrate teaches people what kind of team they are building." },
  { kind: "story", text: "Tell the story of someone who kept a promise to their future self.", framework: "ppf", technique: "show-emotions", setup: "Someone wrote a goal on a sticky note and expected motivation to carry it.", struggle: "Most mornings felt ordinary, and the goal kept moving further away.", turningPoint: "They set one daily minimum and continued even when the feeling disappeared.", lesson: "Personal growth is often a quiet promise kept without an audience." },
];
